// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuPtIiWt-hmpFV8D2kj7-RfAsRj4eUsw',
    appId: '1:893525215708:web:2695c3c854e26c54372719',
    messagingSenderId: '893525215708',
    projectId: 'hook-diner',
    authDomain: 'hook-diner.firebaseapp.com',
    storageBucket: 'hook-diner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGOcKjPV2ov1iX1FuayS-7QFea5uikYNU',
    appId: '1:893525215708:android:70c6e3aaf4c7e9fb372719',
    messagingSenderId: '893525215708',
    projectId: 'hook-diner',
    storageBucket: 'hook-diner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZR_qDOdDUhI5OwuxTFqBiGkA82Mr6GQE',
    appId: '1:893525215708:ios:6df34897b532820d372719',
    messagingSenderId: '893525215708',
    projectId: 'hook-diner',
    storageBucket: 'hook-diner.appspot.com',
    iosBundleId: 'com.example.hookDiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZR_qDOdDUhI5OwuxTFqBiGkA82Mr6GQE',
    appId: '1:893525215708:ios:6df34897b532820d372719',
    messagingSenderId: '893525215708',
    projectId: 'hook-diner',
    storageBucket: 'hook-diner.appspot.com',
    iosBundleId: 'com.example.hookDiner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXuPtIiWt-hmpFV8D2kj7-RfAsRj4eUsw',
    appId: '1:893525215708:web:fc0e10c667c8fa7a372719',
    messagingSenderId: '893525215708',
    projectId: 'hook-diner',
    authDomain: 'hook-diner.firebaseapp.com',
    storageBucket: 'hook-diner.appspot.com',
  );

}